In [62]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [63]:
data=pd.read_csv('Churn_modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [64]:
## Process the Data
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [65]:
## Encode categorical variables
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [66]:
one_hot_encoder_geo=OneHotEncoder(handle_unknown='ignore')
geo_encoded=one_hot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [67]:
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [68]:
# Split the data into features and target
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [69]:
## Split in training and testing set
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## Scale these features

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [70]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl','wb') as file:
     pickle.dump(label_encoder_gender,file)
     
with open('one_hot_encoder_geo.pkl','wb') as file :
     pickle.dump(one_hot_encoder_geo,file)
     
with open('scalerl.pkl','wb') as file:
     pickle.dump(scaler,file)

 ANN Regression Problem statement

In [71]:
## ANN Regression Problem statement
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [72]:
# Build the model

model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1) # Output layer for regression
])

# compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
model.summary()

c:\Users\DELL\venv\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [73]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

## Set up Tenserboard
log_dir="regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [74]:
## Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [75]:
##Train a model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorboard_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 100370.2734 - mae: 100370.2734 - val_loss: 98494.4922 - val_mae: 98494.4922
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 99570.1328 - mae: 99570.1328 - val_loss: 96892.1172 - val_mae: 96892.1172
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 96809.7422 - mae: 96809.7422 - val_loss: 92861.4297 - val_mae: 92861.4297
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 91452.3750 - mae: 91452.3750 - val_loss: 86215.9688 - val_mae: 86215.9688
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 83684.4688 - mae: 83684.4688 - val_loss: 77664.3203 - val_mae: 77664.3203
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 74598.3281 - mae: 74598.3281 - val_loss: 68836.2344 - val_mae: 68836.2344
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 65877.4609 - mae: 65877.4609 - val_loss: 61230.7461 - val_mae: 61230.7461
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 58916.3984 - mae: 58916.3984 - val_loss: 55849.4258 - val_mae: 55849.4258
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 54459.7812 - mae: 54459.7812 - val_loss: 52895.0508 - val_mae: 52895.0508
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 52051.1758 - mae: 52051.1758 - val_loss: 51576.3867 - val_mae: 51576.3867
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50985.1875 - mae: 50985.1875 - val_loss: 51104.9453 - val_mae: 51104.9453
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50570.8398 - mae: 50570.8398 - val_loss: 50937.9766 - val_mae: 50937.9766
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50379.4727 - mae: 50379.4727 - val_loss: 50850.5273 - val_mae: 50850.5273
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50268.2383 - mae: 50268.2383 - val_loss: 50786.7383 - val_mae: 50786.7383
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50186.9375 - mae: 50186.9375 - val_loss: 50731.3047 - val_mae: 50731.3047
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50118.5508 - mae: 50118.5508 - val_loss: 50682.0859 - val_mae: 50682.0859
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50067.0664 - mae: 50067.0664 - val_loss: 50639.0039 - val_mae: 50639.0039
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 50017.0859 - mae: 50017.0859 - val_loss: 50605.8711 - val_mae: 50605.8711
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49973.6992 - mae: 49973.6992 - val_loss: 50577.5312 - val_mae: 50577.5312
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49934.8750 - mae: 49934.8750 - val_loss: 50539.9531 - val_mae: 50539.9531
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 49890.8008 - mae: 49890.8008 - val_loss: 50507.7617 - val_mae: 50507.7617
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 49854.3086 - mae: 49854.3086 - val_loss: 50486.2969 - val_mae: 50486.2969
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49823.7852 - mae: 49823.7852 - val_loss: 50454.6055 - val_mae: 50454.6055
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49795.1836 - mae: 49795.1836 - val_loss: 50437.2148 - val_mae: 50437.2148
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49766.9922 - mae: 49766.9922 - val_loss: 50417.0039 - val_mae: 50417.0039
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49746.1445 - mae: 49746.1445 - val_loss: 50400.3086 - val_mae: 50400.3086
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 49722.1641 - mae: 49722.1641 - val_loss: 50400.2383 - val_mae: 50400.2383
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49701.5977 - mae: 49701.5977 - val_loss: 50385.7188 - val_mae: 50385.7188
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 49683.8203 - mae: 49683.8203 - val_loss: 50363.9102 - val_mae: 50363.9102
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49666.5508 - mae: 49666.5508 - val_loss: 50361.5078 - val_mae: 50361.5078
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49645.1367 - mae: 49645.1367 - val_loss: 50360.4141 - val_mae: 50360.4141
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49632.2227 - mae: 49632.2227 - val_loss: 50353.6289 - val_mae: 50353.6289
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 49617.9844 - mae: 49617.9844 - val_loss: 50339.7383 - val_mae: 50339.7383
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 49604.4336 - mae: 49604.4336 - val_loss: 50342.2383 - val_mae: 50342.2383
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49587.3164 - mae: 49587.3164 - val_loss: 50341.1172 - val_mae: 50341.1172
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49577.8281 - mae: 49577.8281 - val_loss: 50325.1719 - val_mae: 50325.1719
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49565.8164 - mae: 49565.8164 - val_loss: 50317.8594 - val_mae: 50317.8594
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 49554.4570 - mae: 49554.4570 - val_loss: 50315.7852 - val_mae: 50315.7852
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49542.1523 - mae: 49542.1523 - val_loss: 50315.1758 - val_mae: 50315.1758
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49531.4961 - mae: 49531.4961 - val_loss: 50304.9922 - val_mae: 50304.9922
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 49521.2461 - mae: 49521.2461 - val_loss: 50298.3906 - val_mae: 50298.3906
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 49512.6758 - mae: 49512.6758 - val_loss: 50293.8438 - val_mae: 50293.8438
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49504.6406 - mae: 49504.6406 - val_loss: 50299.6094 - val_mae: 50299.6094
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 49495.6250 - mae: 49495.6250 - val_loss: 50284.4922 - val_mae: 50284.4922
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49485.3633 - mae: 49485.3633 - val_loss: 50273.7539 - val_mae: 50273.7539
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 49480.6680 - mae: 49480.6680 - val_loss: 50282.6484 - val_mae: 50282.6484
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49471.1680 - mae: 49471.1680 - val_loss: 50273.2461 - val_mae: 50273.2461
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 49464.2930 - mae: 49464.2930 - val_loss: 50271.2344 - val_mae: 50271.2344
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 49454.8555 - mae: 49454.8555 - val_loss: 50277.9609 - val_mae: 50277.9609
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49447.3203 - mae: 49447.3203 - val_loss: 50278.5508 - val_mae: 50278.5508
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49441.8281 - mae: 49441.8281 - val_loss: 50277.6641 - val_mae: 50277.6641
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49433.7891 - mae: 49433.7891 - val_loss: 50271.2773 - val_mae: 50271.2773
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49428.3516 - mae: 49428.3516 - val_loss: 50272.2148 - val_mae: 50272.2148

In [76]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [77]:
#Load Tensorboard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [78]:
%tensorboard --logdir logs/

Reusing TensorBoard on port 6007 (pid 8040), started 0:03:04 ago. (Use '!kill 8040' to kill it.)